#! /usr/bin/bash

from=$1
to=$2

if [ -z $REPO_PROJECT ]; then
    repo forall -c `realpath "${BASH_SOURCE[0]}"` $from $to
else
    if git rev-parse --quiet $from $to 1>/dev/null 2>/dev/null; then
        if ! git diff --quiet $from $to; then
            echo "--------------------------------------------------------"
            echo "Diff for $REPO_PROJECT:"
            git --no-pager diff $from $to
        fi
    fi
fi
